name: GitHub CRC FrontEnd S3 Update
on:
  push:
    branches: 
      -main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete --exclude '.git*/*'
        env:
          AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}}
